export var countries = [
  { label: "Afghanistan", countryId: "AF" },
  { label: "Åland Islands", countryId: "AX" },
  { label: "Albania", countryId: "AL" },
  { label: "Algeria", countryId: "DZ" },
  { label: "American Samoa", countryId: "AS" },
  { label: "Andorra", countryId: "AD" },
  { label: "Angola", countryId: "AO" },
  { label: "Anguilla", countryId: "AI" },
  { label: "Antarctica", countryId: "AQ" },
  { label: "Antigua and Barbuda", countryId: "AG" },
  { label: "Argentina", countryId: "AR" },
  { label: "Armenia", countryId: "AM" },
  { label: "Aruba", countryId: "AW" },
  { label: "Australia", countryId: "AU" },
  { label: "Austria", countryId: "AT" },
  { label: "Azerbaijan", countryId: "AZ" },
  { label: "Bahamas", countryId: "BS" },
  { label: "Bahrain", countryId: "BH" },
  { label: "Bangladesh", countryId: "BD" },
  { label: "Barbados", countryId: "BB" },
  { label: "Belarus", countryId: "BY" },
  { label: "Belgium", countryId: "BE" },
  { label: "Belize", countryId: "BZ" },
  { label: "Benin", countryId: "BJ" },
  { label: "Bermuda", countryId: "BM" },
  { label: "Bhutan", countryId: "BT" },
  { label: "Bolivia", countryId: "BO" },
  { label: "Bosnia and Herzegovina", countryId: "BA" },
  { label: "Botswana", countryId: "BW" },
  { label: "Bouvet Island", countryId: "BV" },
  { label: "Brazil", countryId: "BR" },
  { label: "British Indian Ocean Territory", countryId: "IO" },
  { label: "Brunei Darussalam", countryId: "BN" },
  { label: "Bulgaria", countryId: "BG" },
  { label: "Burkina Faso", countryId: "BF" },
  { label: "Burundi", countryId: "BI" },
  { label: "Cambodia", countryId: "KH" },
  { label: "Cameroon", countryId: "CM" },
  { label: "Canada", countryId: "CA" },
  { label: "Cape Verde", countryId: "CV" },
  { label: "Cayman Islands", countryId: "KY" },
  { label: "Central African Republic", countryId: "CF" },
  { label: "Chad", countryId: "TD" },
  { label: "Chile", countryId: "CL" },
  { label: "China", countryId: "CN" },
  { label: "Christmas Island", countryId: "CX" },
  { label: "Cocos (Keeling) Islands", countryId: "CC" },
  { label: "Colombia", countryId: "CO" },
  { label: "Comoros", countryId: "KM" },
  { label: "Congo", countryId: "CG" },
  { label: "Congo, The Democratic Republic of the", countryId: "CD" },
  { label: "Cook Islands", countryId: "CK" },
  { label: "Costa Rica", countryId: "CR" },
  { label: "Cote D'Ivoire", countryId: "CI" },
  { label: "Croatia", countryId: "HR" },
  { label: "Cuba", countryId: "CU" },
  { label: "Cyprus", countryId: "CY" },
  { label: "Czech Republic", countryId: "CZ" },
  { label: "Denmark", countryId: "DK" },
  { label: "Djibouti", countryId: "DJ" },
  { label: "Dominica", countryId: "DM" },
  { label: "Dominican Republic", countryId: "DO" },
  { label: "Ecuador", countryId: "EC" },
  { label: "Egypt", countryId: "EG" },
  { label: "El Salvador", countryId: "SV" },
  { label: "Equatorial Guinea", countryId: "GQ" },
  { label: "Eritrea", countryId: "ER" },
  { label: "Estonia", countryId: "EE" },
  { label: "Ethiopia", countryId: "ET" },
  { label: "Falkland Islands (Malvinas)", countryId: "FK" },
  { label: "Faroe Islands", countryId: "FO" },
  { label: "Fiji", countryId: "FJ" },
  { label: "Finland", countryId: "FI" },
  { label: "France", countryId: "FR" },
  { label: "French Guiana", countryId: "GF" },
  { label: "French Polynesia", countryId: "PF" },
  { label: "French Southern Territories", countryId: "TF" },
  { label: "Gabon", countryId: "GA" },
  { label: "Gambia", countryId: "GM" },
  { label: "Georgia", countryId: "GE" },
  { label: "Germany", countryId: "DE" },
  { label: "Ghana", countryId: "GH" },
  { label: "Gibraltar", countryId: "GI" },
  { label: "Greece", countryId: "GR" },
  { label: "Greenland", countryId: "GL" },
  { label: "Grenada", countryId: "GD" },
  { label: "Guadeloupe", countryId: "GP" },
  { label: "Guam", countryId: "GU" },
  { label: "Guatemala", countryId: "GT" },
  { label: "Guernsey", countryId: "GG" },
  { label: "Guinea", countryId: "GN" },
  { label: "Guinea-Bissau", countryId: "GW" },
  { label: "Guyana", countryId: "GY" },
  { label: "Haiti", countryId: "HT" },
  { label: "Heard Island and Mcdonald Islands", countryId: "HM" },
  { label: "Holy See (Vatican City State)", countryId: "VA" },
  { label: "Honduras", countryId: "HN" },
  { label: "Hong Kong", countryId: "HK" },
  { label: "Hungary", countryId: "HU" },
  { label: "Iceland", countryId: "IS" },
  { label: "India", countryId: "IN" },
  { label: "Indonesia", countryId: "ID" },
  { label: "Iran, Islamic Republic Of", countryId: "IR" },
  { label: "Iraq", countryId: "IQ" },
  { label: "Ireland", countryId: "IE" },
  { label: "Isle of Man", countryId: "IM" },
  { label: "Israel", countryId: "IL" },
  { label: "Italy", countryId: "IT" },
  { label: "Jamaica", countryId: "JM" },
  { label: "Japan", countryId: "JP" },
  { label: "Jersey", countryId: "JE" },
  { label: "Jordan", countryId: "JO" },
  { label: "Kazakhstan", countryId: "KZ" },
  { label: "Kenya", countryId: "KE" },
  { label: "Kiribati", countryId: "KI" },
  { label: "Korea, Democratic People'S Republic of", countryId: "KP" },
  { label: "Korea, Republic of", countryId: "KR" },
  { label: "Kuwait", countryId: "KW" },
  { label: "Kyrgyzstan", countryId: "KG" },
  { label: "Lao People'S Democratic Republic", countryId: "LA" },
  { label: "Latvia", countryId: "LV" },
  { label: "Lebanon", countryId: "LB" },
  { label: "Lesotho", countryId: "LS" },
  { label: "Liberia", countryId: "LR" },
  { label: "Libyan Arab Jamahiriya", countryId: "LY" },
  { label: "Liechtenstein", countryId: "LI" },
  { label: "Lithuania", countryId: "LT" },
  { label: "Luxembourg", countryId: "LU" },
  { label: "Macao", countryId: "MO" },
  { label: "Macedonia, The Former Yugoslav Republic of", countryId: "MK" },
  { label: "Madagascar", countryId: "MG" },
  { label: "Malawi", countryId: "MW" },
  { label: "Malaysia", countryId: "MY" },
  { label: "Maldives", countryId: "MV" },
  { label: "Mali", countryId: "ML" },
  { label: "Malta", countryId: "MT" },
  { label: "Marshall Islands", countryId: "MH" },
  { label: "Martinique", countryId: "MQ" },
  { label: "Mauritania", countryId: "MR" },
  { label: "Mauritius", countryId: "MU" },
  { label: "Mayotte", countryId: "YT" },
  { label: "Mexico", countryId: "MX" },
  { label: "Micronesia, Federated States of", countryId: "FM" },
  { label: "Moldova, Republic of", countryId: "MD" },
  { label: "Monaco", countryId: "MC" },
  { label: "Mongolia", countryId: "MN" },
  { label: "Montserrat", countryId: "MS" },
  { label: "Morocco", countryId: "MA" },
  { label: "Mozambique", countryId: "MZ" },
  { label: "Myanmar", countryId: "MM" },
  { label: "Namibia", countryId: "NA" },
  { label: "Nauru", countryId: "NR" },
  { label: "Nepal", countryId: "NP" },
  { label: "Netherlands", countryId: "NL" },
  { label: "Netherlands Antilles", countryId: "AN" },
  { label: "New Caledonia", countryId: "NC" },
  { label: "New Zealand", countryId: "NZ" },
  { label: "Nicaragua", countryId: "NI" },
  { label: "Niger", countryId: "NE" },
  { label: "Nigeria", countryId: "NG" },
  { label: "Niue", countryId: "NU" },
  { label: "Norfolk Island", countryId: "NF" },
  { label: "Northern Mariana Islands", countryId: "MP" },
  { label: "Norway", countryId: "NO" },
  { label: "Oman", countryId: "OM" },
  { label: "Pakistan", countryId: "PK" },
  { label: "Palau", countryId: "PW" },
  { label: "Palestinian Territory, Occupied", countryId: "PS" },
  { label: "Panama", countryId: "PA" },
  { label: "Papua New Guinea", countryId: "PG" },
  { label: "Paraguay", countryId: "PY" },
  { label: "Peru", countryId: "PE" },
  { label: "Philippines", countryId: "PH" },
  { label: "Pitcairn", countryId: "PN" },
  { label: "Poland", countryId: "PL" },
  { label: "Portugal", countryId: "PT" },
  { label: "Puerto Rico", countryId: "PR" },
  { label: "Qatar", countryId: "QA" },
  { label: "Reunion", countryId: "RE" },
  { label: "Romania", countryId: "RO" },
  { label: "Russian Federation", countryId: "RU" },
  { label: "RWANDA", countryId: "RW" },
  { label: "Saint Helena", countryId: "SH" },
  { label: "Saint Kitts and Nevis", countryId: "KN" },
  { label: "Saint Lucia", countryId: "LC" },
  { label: "Saint Pierre and Miquelon", countryId: "PM" },
  { label: "Saint Vincent and the Grenadines", countryId: "VC" },
  { label: "Samoa", countryId: "WS" },
  { label: "San Marino", countryId: "SM" },
  { label: "Sao Tome and Principe", countryId: "ST" },
  { label: "Saudi Arabia", countryId: "SA" },
  { label: "Senegal", countryId: "SN" },
  { label: "Serbia and Montenegro", countryId: "CS" },
  { label: "Seychelles", countryId: "SC" },
  { label: "Sierra Leone", countryId: "SL" },
  { label: "Singapore", countryId: "SG" },
  { label: "Slovakia", countryId: "SK" },
  { label: "Slovenia", countryId: "SI" },
  { label: "Solomon Islands", countryId: "SB" },
  { label: "Somalia", countryId: "SO" },
  { label: "South Africa", countryId: "ZA" },
  { label: "South Georgia and the South Sandwich Islands", countryId: "GS" },
  { label: "Spain", countryId: "ES" },
  { label: "Sri Lanka", countryId: "LK" },
  { label: "Sudan", countryId: "SD" },
  { label: "Suriname", countryId: "SR" },
  { label: "Svalbard and Jan Mayen", countryId: "SJ" },
  { label: "Swaziland", countryId: "SZ" },
  { label: "Sweden", countryId: "SE" },
  { label: "Switzerland", countryId: "CH" },
  { label: "Syrian Arab Republic", countryId: "SY" },
  { label: "Taiwan, Province of China", countryId: "TW" },
  { label: "Tajikistan", countryId: "TJ" },
  { label: "Tanzania, United Republic of", countryId: "TZ" },
  { label: "Thailand", countryId: "TH" },
  { label: "Timor-Leste", countryId: "TL" },
  { label: "Togo", countryId: "TG" },
  { label: "Tokelau", countryId: "TK" },
  { label: "Tonga", countryId: "TO" },
  { label: "Trinidad and Tobago", countryId: "TT" },
  { label: "Tunisia", countryId: "TN" },
  { label: "Turkey", countryId: "TR" },
  { label: "Turkmenistan", countryId: "TM" },
  { label: "Turks and Caicos Islands", countryId: "TC" },
  { label: "Tuvalu", countryId: "TV" },
  { label: "Uganda", countryId: "UG" },
  { label: "Ukraine", countryId: "UA" },
  { label: "United Arab Emirates", countryId: "AE" },
  { label: "United Kingdom", countryId: "GB" },
  { label: "United States", countryId: "US" },
  { label: "United States Minor Outlying Islands", countryId: "UM" },
  { label: "Uruguay", countryId: "UY" },
  { label: "Uzbekistan", countryId: "UZ" },
  { label: "Vanuatu", countryId: "VU" },
  { label: "Venezuela", countryId: "VE" },
  { label: "Viet Nam", countryId: "VN" },
  { label: "Virgin Islands, British", countryId: "VG" },
  { label: "Virgin Islands, U.S.", countryId: "VI" },
  { label: "Wallis and Futuna", countryId: "WF" },
  { label: "Western Sahara", countryId: "EH" },
  { label: "Yemen", countryId: "YE" },
  { label: "Zambia", countryId: "ZM" },
  { label: "Zimbabwe", countryId: "ZW" },
];
